language: php

sudo: required

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer dump-autoload
  - composer install --no-interaction --prefer-source --dev

after_script:
  - if [[ -f coverage.clover ]]; then
      curl -sSOL https://scrutinizer-ci.com/ocular.phar &&
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
    fi
