language: php

sudo: required

php:
  - 7.0
  - 7.1

services:
  - docker

before_script:
  - docker run -d --restart=always -p 3301:3301 --name tarantool tarantool/tarantool:latest
  - composer self-update
  - composer install --no-interaction --prefer-source --optimize-autoloader

after_script:
  - if [[ -f coverage.clover ]]; then
      curl -sSOL https://scrutinizer-ci.com/ocular.phar &&
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
    fi
